"""Add cascade delete to alerts

Revision ID: d3e298e2666f
Revises: f3ece9bf539b
Create Date: 2025-11-26 20:12:49.792163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3e298e2666f'
down_revision: Union[str, Sequence[str], None] = 'f3ece9bf539b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('alert_history_alert_id_fkey'), 'alert_history', type_='foreignkey')
    op.create_foreign_key(None, 'alert_history', 'alerts', ['alert_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alert_history', type_='foreignkey')
    op.create_foreign_key(op.f('alert_history_alert_id_fkey'), 'alert_history', 'alerts', ['alert_id'], ['id'])
    # ### end Alembic commands ###
